spring:
  application:
    name: ordering
  datasource:
    url: jdbc:postgresql://localhost:5432/ordering
    username: postgres
    password: postgres
  jpa:
    database-platform: 
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    flyway.user: postgres
    flyway.password: postgres
    flyway.url: jdbc:postgresql://localhost:5432/ordering

algashop:
  integrations:
    shipping.provider: RAPIDEX
    rapidex.url: http://localhost:8780
    product-catalog.url: http://localhost:8780