spring:
  datasource:
    url: ${DATASOURCE_JDBC_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    username: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
    url: ${DATASOURCE_JDBC_URL}

algashop:
  integrations:
    rapidex.url: ${RAPIDEX_URL}
    product-catalog.url: ${PRODUCT_CATALOG_URL}